/*
    NaturalOWL. 
    Copyright (C) 2008  Dimitrios Galanis and Giorgos Karakatsiotis

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
*/

package gr.aueb.cs.nlg.ProtegeAuthoringTool;


public class AdvancedOptionsPanel extends javax.swing.JPanel {
    
    /** Creates new form AdvancedOptionsPanel */
    public AdvancedOptionsPanel() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        SN = new javax.swing.JLabel();
        SN_TEXT = new javax.swing.JTextField();
        SG = new javax.swing.JLabel();
        SG_TEXT = new javax.swing.JTextField();
        SA = new javax.swing.JLabel();
        SA_TEXT = new javax.swing.JTextField();
        PN = new javax.swing.JLabel();
        PN_TEXT = new javax.swing.JTextField();
        PG = new javax.swing.JLabel();
        PG_TEXT = new javax.swing.JTextField();
        PA = new javax.swing.JLabel();
        PA_TEXT = new javax.swing.JTextField();

        setLayout(null);

        SN.setFont(new java.awt.Font("Verdana", 1, 10));
        SN.setText("Singular nominative");
        add(SN);
        SN.setBounds(78, 214, 174, 14);

        SN_TEXT.setMinimumSize(new java.awt.Dimension(300, 20));
        SN_TEXT.setPreferredSize(new java.awt.Dimension(300, 20));
        add(SN_TEXT);
        SN_TEXT.setBounds(267, 211, 300, 20);

        SG.setFont(new java.awt.Font("Verdana", 1, 10));
        SG.setText("Singular genitive");
        add(SG);
        SG.setBounds(78, 244, 174, 14);

        SG_TEXT.setMinimumSize(new java.awt.Dimension(300, 20));
        SG_TEXT.setPreferredSize(new java.awt.Dimension(300, 20));
        add(SG_TEXT);
        SG_TEXT.setBounds(267, 241, 300, 20);

        SA.setFont(new java.awt.Font("Verdana", 1, 10));
        SA.setText("Singular accusative");
        add(SA);
        SA.setBounds(78, 274, 174, 14);

        SA_TEXT.setMinimumSize(new java.awt.Dimension(300, 20));
        SA_TEXT.setPreferredSize(new java.awt.Dimension(300, 20));
        add(SA_TEXT);
        SA_TEXT.setBounds(267, 271, 300, 20);

        PN.setFont(new java.awt.Font("Verdana", 1, 10));
        PN.setText("Plural nominative");
        add(PN);
        PN.setBounds(78, 304, 174, 14);

        PN_TEXT.setMinimumSize(new java.awt.Dimension(300, 20));
        PN_TEXT.setPreferredSize(new java.awt.Dimension(300, 20));
        add(PN_TEXT);
        PN_TEXT.setBounds(267, 301, 300, 20);

        PG.setFont(new java.awt.Font("Verdana", 1, 10));
        PG.setText("Plural genitive");
        add(PG);
        PG.setBounds(78, 334, 174, 14);

        PG_TEXT.setMinimumSize(new java.awt.Dimension(300, 20));
        PG_TEXT.setPreferredSize(new java.awt.Dimension(300, 20));
        PG_TEXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PG_TEXTActionPerformed(evt);
            }
        });

        add(PG_TEXT);
        PG_TEXT.setBounds(267, 331, 300, 20);

        PA.setFont(new java.awt.Font("Verdana", 1, 10));
        PA.setText("Plural accusative");
        add(PA);
        PA.setBounds(78, 364, 174, 14);

        PA_TEXT.setMinimumSize(new java.awt.Dimension(300, 20));
        PA_TEXT.setPreferredSize(new java.awt.Dimension(300, 20));
        add(PA_TEXT);
        PA_TEXT.setBounds(267, 361, 300, 20);

    }//GEN-END:initComponents

    private void PG_TEXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PG_TEXTActionPerformed
        // Add your handling code here:
    }//GEN-LAST:event_PG_TEXTActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PA;
    private javax.swing.JTextField PA_TEXT;
    private javax.swing.JLabel PG;
    private javax.swing.JTextField PG_TEXT;
    private javax.swing.JLabel PN;
    private javax.swing.JTextField PN_TEXT;
    private javax.swing.JLabel SA;
    private javax.swing.JTextField SA_TEXT;
    private javax.swing.JLabel SG;
    private javax.swing.JTextField SG_TEXT;
    private javax.swing.JLabel SN;
    private javax.swing.JTextField SN_TEXT;
    // End of variables declaration//GEN-END:variables
    
}
